### ISSUE TITLE
Errors doesn't help find cause of problem

### ISSUE THREAD

**Issue by IRus** [bootique/bootique#135]
I found that errors with guice most of time not really useful to searching cause of problem, example:

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/bootique/application/CommandMetadata
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:688)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:380)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:164)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:613)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:569)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:555)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:884)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:805)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:282)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:214)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:890)
	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:134)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at io.bootique.Bootique.createInjector(Bootique.java:407)
	at io.bootique.Bootique.createRuntime(Bootique.java:317)
	at io.bootique.Bootique.run(Bootique.java:342)
	at com.objectstyle.oc.site.FrontendApplication.main(FrontendApplication.java:39)
Caused by: java.lang.ClassNotFoundException: io.bootique.application.CommandMetadata
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more
```

I know that one of my modules uses outdated class, but error message don't help me finding such module.

**Comment by andrus** [comment]
Per https://github.com/bootique/bootique/issues/25 we wanted to classify common errors and provide more user friendly messages. This case though... I am not sure how we programmatically improve the error message.

**Comment by IRus** [comment]
That's because a lot happening in `createInjector` call, I think we can improve that part, if we will use own DI library.

**Comment by andrus** [comment]
I guess our only chance of predicting ClassLoader errors in DI is to implement DI in the style of Dagger, with upfront class generation and compile-time binding.

**Comment by wmacgyver** [comment]
I saw on reddit about 5 month ago you had been looking into dagger2, are you still considering it?

**Comment by William6Lu** [comment]
no,thanks!



卢伟 | luwei564@163.com
 
From: Mac
Date: 2017-04-12 15:06
To: bootique/bootique
CC: Subscribed
Subject: Re: [bootique/bootique] Errors doesn't help find cause of problem (#135)
I saw on reddit about 5 month ago you had been looking into dagger2, are you still considering it?

**Comment by andrus** [comment]
@wmacgyver Conceptually, yes. While Guice is fine, we'd like to have something just a bit lighter than Guice. Though Dagger2 also has its issues, so we haven't pursued it yet. If you have any input on this perhaps we can open a different issue on GitHub or start a discussion on [Bootique forum](https://groups.google.com/forum/#!forum/bootique-user).

**Comment by wmacgyver** [comment]
@andrus thank you for the quick response. the primary 2 reasons dagger 2 is attractive to me are light way and generated class with no reflection. I just discovered bootique, so I'm at the exploration stage. I'll post on the forum once I know bootique a little better

**Comment by andrus** [comment]
Closing this issue. It was a lovely discussion, but I don't think we have anything actionable here.
