### ISSUE TITLE
Contributing command as lambda results in a cryptic exception

### ISSUE THREAD

**Issue by andrus** [bootique/bootique#153]
```java
BQCoreModule.extend(binder)
                .addCommand(cli -> CommandOutcome.suceeded());
```
The code above results in the an exception below, because command lambda has no metadata. At the minimum we need to pre-validate this case and throw something more user-friendly. And maybe extend the API to allow supplying CommandMetadata to the nameless lambda.

com.google.inject.CreationException: Unable to create injector, see the following errors:

```
1) Error in custom provider, joptsimple.IllegalOptionSpecificationException: $ is not a legal option character
  while locating io.bootique.jopt.JoptCliProvider
  at io.bootique.BQCoreModule.configure(BQCoreModule.java:240)
  while locating io.bootique.cli.Cli
    for parameter 0 at io.bootique.BQCoreModule.provideConfigurationSource(BQCoreModule.java:276)
  at io.bootique.BQCoreModule.provideConfigurationSource(BQCoreModule.java:276)
  at io.bootique.BQCoreModule.provideConfigurationSource(BQCoreModule.java:276)
  while locating io.bootique.config.ConfigurationSource
    for parameter 0 at io.bootique.JsonNodeConfigurationFactoryProvider.<init>(JsonNodeConfigurationFactoryProvider.java:42)
  while locating io.bootique.JsonNodeConfigurationFactoryProvider
```

**Comment by aarrsseni** [comment]
@andrus 
Looks like now it works.
```
BQRuntime runtime = testFactory.app()
                .module(binder ->
                        BQCoreModule.extend(binder).addCommand(cli -> CommandOutcome.succeeded()))
                .createRuntime();
```
This code doesn't throw any exceptions.
But this command has only generated unpredictable name, so it's difficult to run it.

**Comment by andrus** [comment]
Cool. I guess in this case we need to explore API extension to allow to pass some explicit metadata (at least the name).
