### ISSUE TITLE
"CLI options match multiple commands" error sometimes reported with a stack

### ISSUE THREAD

**Issue by andrus** [bootique/bootique#259]
Per #25 we are not printing scary stack traces for known startup failures. A very common error when two command flags are specified at the same time (`CLI options match multiple commands`)  is normally reported as one-liner (e.g. in `bootique-jobs-demo`), but in others apps it blows up with the full stack. Some examples:

```
Command exception.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, io.bootique.BootiqueException: CLI options match multiple commands: help, my-command.
  while locating io.bootique.jopt.JoptCliProvider
  at io.bootique.BQCoreModule.configure(BQCoreModule.java:247) (via modules: com.google.inject.util.Modules$OverrideModule -> io.bootique.BQCoreModule)
  while locating io.bootique.cli.Cli
    for parameter 0 at io.bootique.BQCoreModule.provideConfigurationSource(BQCoreModule.java:283)
  at io.bootique.BQCoreModule.provideConfigurationSource(BQCoreModule.java:283) (via modules: com.google.inject.util.Modules$OverrideModule -> io.bootique.BQCoreModule)
  at io.bootique.BQCoreModule.provideConfigurationSource(BQCoreModule.java:283) (via modules: com.google.inject.util.Modules$OverrideModule -> io.bootique.BQCoreModule)
  while locating io.bootique.config.ConfigurationSource
    for parameter 0 at io.bootique.JsonNodeConfigurationFactoryProvider.<init>(JsonNodeConfigurationFactoryProvider.java:58)
  while locating io.bootique.JsonNodeConfigurationFactoryProvider
  at io.bootique.BQCoreModule.configure(BQCoreModule.java:244) (via modules: com.google.inject.util.Modules$OverrideModule -> io.bootique.BQCoreModule)
  while locating io.bootique.config.ConfigurationFactory
    for parameter 0 at io.bootique.logback.LogbackModule.provideRootLogger(LogbackModule.java:42)
  at io.bootique.logback.LogbackModule.provideRootLogger(LogbackModule.java:42)
  at io.bootique.logback.LogbackModule.provideRootLogger(LogbackModule.java:42)
  while locating ch.qos.logback.classic.Logger
    for parameter 0 at io.bootique.logback.LogbackModule$LogInitTrigger.<init>(LogbackModule.java:50)
  at io.bootique.logback.LogbackModule.configure(LogbackModule.java:33)
  while locating io.bootique.logback.LogbackModule$LogInitTrigger
# more stack trace follows...
```
Second example:
```
Error running command '-h -u -f 2019-10-02 -t 2019-10-02': Command exception.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, io.bootique.BootiqueException: CLI options match multiple commands: help, update-standings.
  at io.bootique.BQCoreModule.provideCli(BQCoreModule.java:219) (via modules: com.google.inject.util.Modules$OverrideModule -> io.bootique.BQCoreModule)
  while locating io.bootique.cli.Cli
    for the 1st parameter of io.bootique.BQCoreModule.provideConfigurationSource(BQCoreModule.java:189)
  at io.bootique.BQCoreModule.provideConfigurationSource(BQCoreModule.java:189) (via modules: com.google.inject.util.Modules$OverrideModule -> io.bootique.BQCoreModule)
  while locating io.bootique.config.ConfigurationSource
    for the 1st parameter of io.bootique.JsonNodeConfigurationFactoryProvider.<init>(JsonNodeConfigurationFactoryProvider.java:82)
  while locating io.bootique.JsonNodeConfigurationFactoryProvider
  at io.bootique.BQCoreModule.configure(BQCoreModule.java:158) (via modules: com.google.inject.util.Modules$OverrideModule -> io.bootique.BQCoreModule)
  while locating io.bootique.config.ConfigurationFactory
    for the 1st parameter of io.bootique.metrics.MetricsModule.provideMetricRegistryFactory(MetricsModule.java:51)
  at io.bootique.metrics.MetricsModule.provideMetricRegistryFactory(MetricsModule.java:51)
  while locating io.bootique.metrics.MetricRegistryFactory
    for the 1st parameter of io.bootique.metrics.MetricRegistryProvider.<init>(MetricRegistryProvider.java:33)
  while locating io.bootique.metrics.MetricRegistryProvider
  at io.bootique.metrics.MetricsModule.configure(MetricsModule.java:45)
  while locating com.codahale.metrics.MetricRegistry
Caused by: io.bootique.BootiqueException: CLI options match multiple commands: help, update-standings.
	at io.bootique.jopt.JoptCliFactory.commandName(JoptCliFactory.java:159)
	at io.bootique.jopt.JoptCliFactory.createCli(JoptCliFactory.java:75)
	at io.bootique.BQCoreModule.provideCli(BQCoreModule.java:219)
	at io.bootique.BQCoreModule$$FastClassByGuice$$e11d7d96.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
...
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at io.bootique.Bootique.createInjector(Bootique.java:472)
	at io.bootique.Bootique.createRuntime(Bootique.java:330)
	at io.bootique.Bootique.exec(Bootique.java:349)
	at com.foo.App.main(App.java:38)

2) Error in custom provider, io.bootique.BootiqueException: CLI options match multiple commands: help, update-standings.
  at io.bootique.BQCoreModule.provideCli(BQCoreModule.java:219) (via modules: com.google.inject.util.Modules$OverrideModule -> io.bootique.BQCoreModule)
  while locating io.bootique.cli.Cli
    for the 1st parameter of io.bootique.BQCoreModule.provideConfigurationSource(BQCoreModule.java:189)
  at io.bootique.BQCoreModule.provideConfigurationSource(BQCoreModule.java:189) (via modules: com.google.inject.util.Modules$OverrideModule -> io.bootique.BQCoreModule)
  while locating io.bootique.config.ConfigurationSource
    for the 1st parameter of io.bootique.JsonNodeConfigurationFactoryProvider.<init>(JsonNodeConfigurationFactoryProvider.java:82)
  while locating io.bootique.JsonNodeConfigurationFactoryProvider
  at io.bootique.BQCoreModule.configure(BQCoreModule.java:158) (via modules: com.google.inject.util.Modules$OverrideModule -> io.bootique.BQCoreModule)
  while locating io.bootique.config.ConfigurationFactory
    for the 1st parameter of io.bootique.logback.LogbackModule.provideRootLogger(LogbackModule.java:61)
  at io.bootique.logback.LogbackModule.provideRootLogger(LogbackModule.java:61)
  while locating ch.qos.logback.classic.Logger
    for the 1st parameter of io.bootique.logback.LogbackModule$LogInitTrigger.<init>(LogbackModule.java:68)
  at io.bootique.logback.LogbackModule.configure(LogbackModule.java:52)
  while locating io.bootique.logback.LogbackModule$LogInitTrigger
Caused by: io.bootique.BootiqueException: CLI options match multiple commands: help, update-standings.
	at io.bootique.jopt.JoptCliFactory.commandName(JoptCliFactory.java:159)
	at io.bootique.jopt.JoptCliFactory.createCli(JoptCliFactory.java:75)
	at io.bootique.BQCoreModule.provideCli(BQCoreModule.java:219)
	at io.bootique.BQCoreModule$$FastClassByGuice$$e11d7d96.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
...
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at io.bootique.Bootique.createInjector(Bootique.java:472)
	at io.bootique.Bootique.createRuntime(Bootique.java:330)
	at io.bootique.Bootique.exec(Bootique.java:349)
	at com.foo.App.main(App.java:38)

2 errors
	...
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at io.bootique.Bootique.createInjector(Bootique.java:472)
	at io.bootique.Bootique.createRuntime(Bootique.java:330)
	at io.bootique.Bootique.exec(Bootique.java:349)
	at com.foo.App.main(App.java:38)
```

**Comment by stariy95** [comment]
Not sure if this one is fixed or there is some other case. Here is what I get and it seems ok to me:
```java
CommandOutcome outcome = Bootique.app("-a", "-b")
        .module(b -> BQCoreModule.extend(b)
                .addCommand(acommand)
                .addCommand(bcommand))
        .exec();

assertFalse(outcome.isSuccess());
assertEquals(1, outcome.getExitCode());
assertTrue(outcome.getMessage().startsWith("CLI options match multiple commands:"));
```

**Comment by andrus** [comment]
I just added a second example from a client app (and confirmed that some other apps don't have this issue). I think it depends on the app structure somehow,

**Comment by stariy95** [comment]
I was able to reproduce this. This happens when you use `bootique-logback` and `bootique-metrics` modules in your app. 
But in general, this doesn't depend on multiple commands or bootique modules. 
We'll get these long traces of Guice errors in case Injector has more than one error. In that case, cause exception passed differently, via messages instead of as a cause in a `CreationException`.
We correctly process this for the `ProvisionException` and should just do the same in this case.
