### ISSUE TITLE
Startup exceptions are swallowed by Guice on Java 11

### ISSUE THREAD

**Issue by andrus** [bootique/bootique#266]
Environment: Java 11 (which is think is relevant), Bootique 1.1-SNAPSHOT.

When running custom code that throws an NPE within a provider method, instead of the error cause, I am getting a generic exception similar to the one below, that doesn't tell me anything about the cause. It appears that something blows up inside the exception handler, so we are only seeing that second exception.

Here is the message inside UncheckedExecutionException:

```
Method threw 'com.google.common.util.concurrent.UncheckedExecutionException' 
exception. Cannot evaluate com.google.inject.ProvisionException.toString()
```

```
Error running command '-s -l': Command exception.
Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2047)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3869)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3873)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4798)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4804)
	at com.google.inject.internal.util.StackTraceElements.forMember(StackTraceElements.java:71)
	at com.google.inject.internal.Messages.formatSource(Messages.java:241)
	at com.google.inject.internal.Messages.formatSource(Messages.java:220)
	at com.google.inject.internal.Messages.formatMessages(Messages.java:90)
	at com.google.inject.ProvisionException.getMessage(ProvisionException.java:61)
	at java.base/java.lang.Throwable.getLocalizedMessage(Throwable.java:396)
	at java.base/java.lang.Throwable.toString(Throwable.java:485)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.io.PrintStream.println(PrintStream.java:897)
	at java.base/java.lang.Throwable$WrappedPrintStream.println(Throwable.java:752)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:659)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:648)
	at io.bootique.log.DefaultBootLogger.stderr(DefaultBootLogger.java:66)
	at io.bootique.Bootique.exec(Bootique.java:385)
	at io.bootique.Bootique.main(Bootique.java:95)
	at com.foo.App.main(App.java:30)
Caused by: java.lang.IllegalArgumentException
	at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:160)
	at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:143)
	at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:418)
	at com.google.inject.internal.util.LineNumbers.<init>(LineNumbers.java:64)
	at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:49)
	at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:45)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3443)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2169)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2128)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2041)
	... 20 more
```

**Comment by andrus** [comment]
This is reproducible when a module in question is compiled at Java 11 source level (so not currently possible to reproduce in Bootique itself that is Java 8). Looks like `$ClassReader.java` in Guice exoplicitly checks that the code is `<= Java 8` (https://en.wikipedia.org/wiki/Java_class_file) 

```java
   public $ClassReader(byte[] b, int off, int len) {
        this.b = b;
        if (this.readShort(off + 6) > 53) {  // <-- "53" is Java 9
            throw new IllegalArgumentException();
        } else {
```

**Comment by andrus** [comment]
Looks like we need Guice 4.2.2 that has java 11 support - https://github.com/google/guice/wiki/Guice422

**Comment by andrus** [comment]
4.2.2 upgrade fixes this.
