### ISSUE TITLE
Can't create "default" command via a method with @Provides

### ISSUE THREAD

**Issue by andrus** [bootique/bootique#282]
Somehow Bootique 2.0 ignores `@Provides` method for the default command, so if the command has a non-standard constructor, Bootique throws an exception on startup. Same command works when I do `addCommand` instead of `setDefaultCommand`.

Here is a diff with a unit test: 

```java
diff --git a/bootique/src/test/java/io/bootique/command/CommandManagerIT.java b/bootique/src/test/java/io/bootique/command/CommandManagerIT.java
index 2f458f0..2dcf03d 100644
--- a/bootique/src/test/java/io/bootique/command/CommandManagerIT.java
+++ b/bootique/src/test/java/io/bootique/command/CommandManagerIT.java
@@ -24,12 +24,15 @@ import io.bootique.BQRuntime;
 import io.bootique.cli.Cli;
 import io.bootique.di.Binder;
 import io.bootique.di.BQModule;
+import io.bootique.di.Provides;
 import io.bootique.help.HelpCommand;
 import io.bootique.meta.application.CommandMetadata;
 import io.bootique.unit.BQInternalTestFactory;
 import org.junit.Rule;
 import org.junit.Test;
 
+import javax.inject.Singleton;
+
 import static org.junit.Assert.assertEquals;
 import static org.junit.Assert.assertFalse;
 import static org.junit.Assert.assertSame;
@@ -138,6 +141,17 @@ public class CommandManagerIT {
         assertSame(defaultCommand, commandManager.getPublicDefaultCommand().get());
     }
 
+    @Test
+    public void testDefaultCommandViaProvidesMethod() {
+
+        BQRuntime runtime = runtimeFactory.app()
+                .modules(M2.class)
+                .createRuntime();
+
+        CommandOutcome o = runtime.run();
+        assertFalse(o.isSuccess());
+        assertEquals("m2-command-label", o.getMessage());
+    }
 
     public static class M0 implements BQModule {
 
@@ -168,4 +182,34 @@ public class CommandManagerIT {
             BQCoreModule.extend(binder).addCommand(mockCommand);
         }
     }
+
+    public static class M2 implements BQModule {
+
+        @Override
+        public void configure(Binder binder) {
+            BQCoreModule.extend(binder).setDefaultCommand(DefaultCommand2.class);
+        }
+
+        @Provides
+        @Singleton
+        DefaultCommand2 provideDefaultCommand2() {
+            return new DefaultCommand2("m2-command-label");
+        }
+    }
+
+    public static class DefaultCommand2 extends CommandWithMetadata {
+
+        private String message;
+
+        // intentionally using non-default constructor, to ensure DI can't instantiate it without a @Provides method
+        public DefaultCommand2(String message) {
+            super(CommandMetadata.builder(DefaultCommand2.class).build());
+            this.message = message;
+        }
+
+        @Override
+        public CommandOutcome run(Cli cli) {
+            return CommandOutcome.failed(-1, message);
+        }
+    }
 }
```

```
io.bootique.di.DIRuntimeException: No applicable constructor is found for constructor injection in class 'io.bootique.command.CommandManagerIT$DefaultCommand2'

at io.bootique.di.spi.InjectorPredicates.createException(InjectorPredicates.java:131)
at io.bootique.di.spi.InjectorPredicates.createException(InjectorPredicates.java:127)
at io.bootique.di.spi.DefaultInjector.throwException(DefaultInjector.java:474)
at io.bootique.di.spi.ConstructorInjectingProvider.findConstructor(ConstructorInjectingProvider.java:69)
at io.bootique.di.spi.ConstructorInjectingProvider.<init>(ConstructorInjectingProvider.java:37)
at io.bootique.di.spi.DefaultBindingBuilder.to(DefaultBindingBuilder.java:51)
at io.bootique.di.spi.DefaultBindingBuilder.to(DefaultBindingBuilder.java:28)
at io.bootique.BQCoreModuleExtender.setDefaultCommand(BQCoreModuleExtender.java:93)
at io.bootique.command.CommandManagerIT$M2.configure(CommandManagerIT.java:190)
```

**Comment by stariy95** [comment]
This one is a missing feature in the Bootique DI. It currently doesn't allow chained bindings. 
I.e. this won't work:
```java
binder.bind(Interface.class).to(AnotherInterface.class);
binder.bind(AnotherInterface.class).to(Implementation.class);
```

**Comment by championjing** [comment]
description

| |
championjing
|
|
championjing@163.com
|
On 3/26/2020 17:51，Nikita Timofeev<notifications@github.com> wrote：

This one is a missing feature in the Bootique DI. It currently doesn't allow chained bindings.
I.e. this won't work:

binder.bind(Interface.class).to(AnotherInterface.class);
binder.bind(AnotherInterface.class).to(Implementation.class);

**Comment by stariy95** [comment]
Fixed in the Bootique DI
