### ISSUE TITLE
BQModuleTester.testConfig() fails when its factories use constructor injection

### ISSUE THREAD

**Issue by andrus** [bootique/bootique#350]
The new `BQModuleTester.testConfig()` method throws when the module being tested contains factories that rely on constructor injection. Factory instantiation happens via Jackson, that does not recognize injection constructor.

```
Caused by: io.bootique.di.DIRuntimeException: Error invoking provider method 'provideConfigurationFactory()' of module 'io.bootique.BQCoreModule'

Injection trace: 

[0] resolving key <BindingKey: io.bootique.config.ConfigurationFactory>
 -> Invoking provider method 'provideConfigurationFactory()' of module 'io.bootique.BQCoreModule'

[1] resolving key <BindingKey: io.bootique.metrics.MetricRegistryFactory>
 -> Get argument 0 for provider method 'provideMetricRegistryFactory()' of module 'io.bootique.metrics.MetricsModule'

[2] resolving key <BindingKey: com.codahale.metrics.MetricRegistry>
 -> Get argument 0 for constructor of class 'io.bootique.metrics.MetricRegistryProvider'

Caused by: java.lang.RuntimeException: Error creating config
at io.bootique.config.jackson.JsonConfigurationFactory.config(JsonConfigurationFactory.java:64)
at my.Configurator.updateConfiguration(Configurator.java:52)
at io.bootique.config.jackson.JsonConfigurationLoader.load(JsonConfigurationLoader.java:45)
at io.bootique.BQCoreModule.provideConfigurationFactory(BQCoreModule.java:180)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at io.bootique.di.spi.ProvidesHandler$ProvidesMethodProvider.get(ProvidesHandler.java:180)
at io.bootique.di.spi.TraceableProvider.get(TraceableProvider.java:49)
at io.bootique.di.spi.DefaultScopeProvider.get(DefaultScopeProvider.java:50)
...
at io.bootique.di.spi.DefaultScopeProvider.get(DefaultScopeProvider.java:50)
at io.bootique.di.spi.DefaultInjector.getInstanceWithCycleProtection(DefaultInjector.java:258)
at io.bootique.di.spi.DefaultInjector.getInstanceWithCycleProtection(DefaultInjector.java:236)
at io.bootique.di.spi.DefaultInjector.getInstance(DefaultInjector.java:232)
at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4709)
at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5944)
at io.bootique.di.spi.DefaultInjector.earlySetup(DefaultInjector.java:409)
at io.bootique.di.spi.DefaultInjector.<init>(DefaultInjector.java:112)
at io.bootique.di.DIBootstrap$InjectorBuilder.build(DIBootstrap.java:255)
at io.bootique.Bootique.createInjector(Bootique.java:398)
at io.bootique.Bootique.createRuntime(Bootique.java:276)
at io.bootique.Bootique.createRuntime(Bootique.java:272)
at io.bootique.junit5.BQModuleTester.testConfig(BQModuleTester.java:86)
at my.ModuleTest.test(ModuleTest.java:11)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
....
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `my.Factory` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
at [Source: UNKNOWN; byte offset: #UNKNOWN]
at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1909)
at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:408)
at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1354)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1420)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4706)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2879)
at io.bootique.config.jackson.JsonConfigurationFactory.config(JsonConfigurationFactory.java:59)
... 106 more
```

**Comment by andrus** [comment]
closing. The issue was cause by a different condition - a custom JsonConfigurationLoader
